load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "lib",
    srcs = ["lib.bzl"],
    visibility = ["//:__subpackages__"],
    deps = [
        "//runfiles_group/private/lib:aspect_step",
        "//runfiles_group/private/lib:constants",
        "//runfiles_group/private/lib:content",
        "//runfiles_group/private/lib:describe",
        "//runfiles_group/private/lib:entry",
        "//runfiles_group/private/lib:finalize",
        "//runfiles_group/private/lib:flag",
        "//runfiles_group/private/lib:limit",
        "//runfiles_group/private/lib:names",
        "//runfiles_group/private/lib:packager",
        "//runfiles_group/private/lib:partial",
        "//runfiles_group/private/lib:resolved",
        "//runfiles_group/private/providers:runfiles_group_info",
    ],
)
