load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":asset_bundle.bzl", "asset_bundle_runfiles_group_describer")
load(":plain_binary.bzl", "plain_binary_runfiles_group_describer")
load(":shared_bundle.bzl", "shared_bundle_runfiles_group_describer")
load(":starlark_app.bzl", "starlark_app_runfiles_group_describer")
load(":starlark_binary.bzl", "starlark_binary_runfiles_group_describer")
load(":starlark_library.bzl", "starlark_library_runfiles_group_describer")

bzl_library(
    name = "asset_bundle",
    srcs = ["asset_bundle.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

bzl_library(
    name = "foreign_plugin",
    srcs = ["foreign_plugin.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "plain_binary",
    srcs = ["plain_binary.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

bzl_library(
    name = "shared_bundle",
    srcs = ["shared_bundle.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

bzl_library(
    name = "starlark_library",
    srcs = ["starlark_library.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//producer/providers",
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

bzl_library(
    name = "starlark_app",
    srcs = ["starlark_app.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//producer/providers",
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

bzl_library(
    name = "starlark_binary",
    srcs = ["starlark_binary.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//producer/providers",
        "@hermetic_launcher//launcher:lib_bzl",
        "@rules_runfiles_group//runfiles_group:lib",
    ],
)

starlark_library_runfiles_group_describer(
    name = "starlark_library_runfiles_group_describer",
    visibility = ["//visibility:public"],
)

starlark_binary_runfiles_group_describer(
    name = "starlark_binary_runfiles_group_describer",
    visibility = ["//visibility:public"],
)

asset_bundle_runfiles_group_describer(
    name = "asset_bundle_runfiles_group_describer",
    visibility = ["//visibility:public"],
)

shared_bundle_runfiles_group_describer(
    name = "shared_bundle_runfiles_group_describer",
    visibility = ["//visibility:public"],
)

starlark_app_runfiles_group_describer(
    name = "starlark_app_runfiles_group_describer",
    visibility = ["//visibility:public"],
)

plain_binary_runfiles_group_describer(
    name = "plain_binary_runfiles_group_describer",
    visibility = ["//visibility:public"],
)
